import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  techBlogSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'autogenerated', 
      dirName: 'tech'
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;


// export default {
//   techBlogSidebar: [
//     {
//       type: 'category',
//       label: 'Getting Started',
//       items: [
//         {
//           type: 'doc',
//           id: 'intro',
//         },
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Docusaurus',
//       items: [
//         {
//           type: 'doc',
//           id: 'tutorial-basics/congratulations',
//         },
//         {
//           type: 'doc',
//           id: 'tutorial-basics/create-a-blog-post',
//         },
//         {
//           type: 'link',
//           label: 'Learn more',
//           href: 'https://example.com',
//         },
//       ],
//     },

//   ],
// }